name: CI/CD Pipeline

# Trigger this workflow on every push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Run tests
  test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # Step 4: Run tests with pytest
      - name: Run tests
        run: |
          pytest tests/

  # Job 2: Build Docker image and run locally
  build_and_run:
    needs: test  # Run this job only if tests pass
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t my-fastapi-app .

      # Step 4: Run the Docker image locally
      - name: Run Docker container
        run: |
          docker run -d -p 8000:8000 --name my-fastapi-app-container my-fastapi-app

      # Step 5: Test if the container is running
      - name: Test Docker container
        run: |
          curl --fail http://localhost:8000 || exit 1

      # Step 6: Stop and remove Docker container after testing
      - name: Clean up Docker
        run: |
          docker stop my-fastapi-app-container
          docker rm my-fastapi-app-container
